# 1.
SELECT Fname, Lname, Country
FROM PARTICIPANT P, ATHLETE A
WHERE P.OlympicID=A.OlympicID;


# 2.
SELECT Fname, Lname, Country
FROM PARTICIPANT P, COACH C
WHERE P.OlympicID=C.OlympicID AND Orientation="Pending";


# 3.
SELECT Country, COUNT(*)
FROM PARTICIPANT P, ATHLETE A, COUNTRY
WHERE P.OlympicID=A.OlympicID AND CName=Country
GROUP BY Country;


# 4.
SELECT P.OlympicID, BirthYear
FROM ((PARTICIPANT P LEFT OUTER JOIN 
       ATHLETE A ON P.OlympicID=A.OlympicID) LEFT OUTER JOIN 
       COACH C ON P.OlympicID=C.OlympicID)
ORDER BY BirthYear ASC;


# 5.
SELECT Country
FROM PARTICIPANT P, ATHLETE A, COUNTRY
WHERE P.OlympicID=A.OlympicID AND CName=Country
GROUP BY Country
HAVING COUNT(*) > 1;


# 6. 
(SELECT Fname, Lname
FROM (PARTICIPANT NATURAL JOIN ATHLETE), INDIVIDUAL_RESULTS R
WHERE R.Olympian=OlympicID)
UNION DISTINCT
(SELECT Fname, Lname
FROM (PARTICIPANT NATURAL JOIN ATHLETE), 
     (TEAM JOIN TEAM_RESULTS ON Team=TeamID)
WHERE OlympicID IN (Member1, Member2, Member3, Member4, Member5, Member6));


# 7.
SELECT CName
FROM COUNTRY
WHERE (AllTimeGold+AllTimeSilver+AllTimeBronze)>=5;


# 8.
SELECT Country, COUNT(*)
FROM ((SELECT Country
      FROM (PARTICIPANT JOIN INDIVIDUAL_RESULTS ON OlympicID=Olympian))
      UNION ALL
      (SELECT Country
      FROM (TEAM JOIN 
            TEAM_RESULTS ON Team=TeamID) JOIN 
            PARTICIPANT ON OlympicID=Member1)
     ) AS ALL_RESULTS
GROUP BY Country;


# 9.
SELECT Fname, Lname
FROM (PARTICIPANT NATURAL JOIN ATHLETE)
WHERE FirstGames="Tokyo 2020";


# 10.
(SELECT Fname, Lname, BirthYear
FROM (PARTICIPANT NATURAL JOIN ATHLETE)
WHERE BirthYear=(SELECT MAX(BirthYear) FROM ATHLETE))
UNION ALL
(SELECT Fname, Lname, BirthYear
FROM (PARTICIPANT NATURAL JOIN ATHLETE)
WHERE BirthYear=(SELECT MIN(BirthYear) FROM ATHLETE));


# 11.
DROP VIEW IF EXISTS TEAM_ATHLETES;
CREATE VIEW TEAM_ATHLETES
AS SELECT Fname, Lname, BirthYear
   FROM (PARTICIPANT NATURAL JOIN ATHLETE)
   ORDER BY BirthYear DESC;

SELECT *
FROM TEAM_ATHLETES;


# 12.
DROP TABLE IF EXISTS INDIVID_W;
CREATE TABLE INDIVID_W (
  EventDate VARCHAR(15) NOT NULL,
  Location VARCHAR(30) NOT NULL,
  Lname VARCHAR(25) NOT NULL,
  Country VARCHAR(30) NOT NULL,
  PRIMARY KEY (Lname)
);

INSERT INTO INDIVID_W(EventDate, Location, Lname, Country)
  SELECT EventDate, Location, Lname, Country
  FROM EVENT_SCHEDULE, (PARTICIPANT NATURAL JOIN ATHLETE)
  WHERE EventDate='July 30' AND Sex='F';

SELECT *
FROM INDIVID_W;


