# 1.
SELECT Fname, Lname, Country
FROM PARTICIPANT, ATHLETE
WHERE PARTICIPANT.OlympicID=ATHLETE.OlympicID;


# 2.
SELECT Fname, Lname, Country
FROM PARTICIPANT, COACH
WHERE PARTICIPANT.OlympicID=COACH.OlympicID AND Orientation="Pending";


# 3.
SELECT Country, COUNT(*)
FROM PARTICIPANT, ATHLETE, COUNTRY
WHERE PARTICIPANT.OlympicID=ATHLETE.OlympicID AND CName=Country
GROUP BY Country;


# 4.
SELECT P.OlympicID, BirthYear
FROM ((PARTICIPANT AS P LEFT OUTER JOIN ATHLETE AS A ON P.OlympicID=A.OlympicID)
                        LEFT OUTER JOIN COACH AS C ON P.OlympicID=C.OlympicID)
ORDER BY BirthYear ASC;


# 5.
SELECT Country
FROM PARTICIPANT, ATHLETE, COUNTRY
WHERE PARTICIPANT.OlympicID=ATHLETE.OlympicID AND CName=Country
GROUP BY Country
HAVING COUNT(*) > 1;


# 6. 
(SELECT Fname, Lname
FROM (PARTICIPANT AS P NATURAL JOIN ATHLETE AS A), INDIVIDUAL_RESULTS AS R
WHERE R.Olympian=P.OlympicID)
UNION DISTINCT
(SELECT Fname, Lname
FROM (PARTICIPANT AS P NATURAL JOIN ATHLETE AS A), 
    (TEAM JOIN TEAM_RESULTS ON Team=TeamID)
WHERE A.OlympicID IN (Member1, Member2, Member3, Member4, Member5, Member6));


# 7.
SELECT CName
FROM COUNTRY
WHERE (AllTimeGold+AllTimeSilver+AllTimeBronze)>=5;


# 8.
SELECT Country, COUNT(*)
FROM ((SELECT Country
      FROM (PARTICIPANT AS P NATURAL JOIN INDIVIDUAL_RESULTS AS IR)
      WHERE OlympicID=Olympian)
      UNION ALL
      (SELECT Country
      FROM (TEAM JOIN TEAM_RESULTS ON Team=TeamID) JOIN PARTICIPANT ON OlympicID=Member1)     ) AS ALL_RESULTS
GROUP BY Country;


# 9.
SELECT Fname, Lname
FROM (PARTICIPANT AS P NATURAL JOIN ATHLETE AS A)
WHERE FirstGames="Tokyo 2020";


# 10.
(SELECT Fname, Lname, BirthYear
FROM (PARTICIPANT NATURAL JOIN ATHLETE)
WHERE BirthYear=(SELECT MAX(BirthYear) FROM ATHLETE))
UNION ALL
(SELECT Fname, Lname, BirthYear
FROM (PARTICIPANT NATURAL JOIN ATHLETE)
WHERE BirthYear=(SELECT MIN(BirthYear) FROM ATHLETE));


# 11.
CREATE VIEW TEAM_ATHLETES
AS SELECT Fname, Lname, BirthYear
   FROM (PARTICIPANT NATURAL JOIN ATHLETE)
   ORDER BY BirthYear DESC;

SELECT *
FROM TEAM_ATHLETES;


# 12.
DROP TABLE IF EXISTS INDIVID_W;
CREATE TABLE INDIVID_W (
  EventDate VARCHAR(15) NOT NULL,
  Location VARCHAR(30) NOT NULL,
  Lname VARCHAR(25) NOT NULL,
  Country VARCHAR(30) NOT NULL,
  PRIMARY KEY (Lname)
);

INSERT INTO INDIVID_W(EventDate, Location, Lname, Country)
  SELECT EventDate, Location, Lname, Country
  FROM EVENT_SCHEDULE AS E, (PARTICIPANT AS P NATURAL JOIN ATHLETE AS A)
  WHERE E.EventDate='July 30' AND A.Sex='F';

SELECT *
FROM INDIVID_W;


